import {
  Product,
  Category,
  Brand,
  Banner,
  Service,
  BlogPost,
  ProductCompatibility,
  ProductImage,
} from '@/types'

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Motor e Mecânica',
    slug: 'motor-e-mecanica',
    description: 'Peças para motor e componentes mecânicos',
    image: null,
    icon: 'wrench',
    parent_id: null,
    order: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    children: [
      {
        id: 'cat-1-1',
        name: 'Pistões e Anéis',
        slug: 'pistoes-e-aneis',
        description: 'Pistões e anéis de segmento',
        image: null,
        icon: null,
        parent_id: 'cat-1',
        order: 1,
        is_active: true,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
      },
      {
        id: 'cat-1-2',
        name: 'Cilindros e Camisas',
        slug: 'cilindros-e-camisas',
        description: 'Cilindros e camisas para motor',
        image: null,
        icon: null,
        parent_id: 'cat-1',
        order: 2,
        is_active: true,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
      },
      {
        id: 'cat-1-3',
        name: 'Virabrequins',
        slug: 'virabrequins',
        description: 'Virabrequins e componentes',
        image: null,
        icon: null,
        parent_id: 'cat-1',
        order: 3,
        is_active: true,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
      },
    ],
  },
  {
    id: 'cat-2',
    name: 'Sistema de Freio',
    slug: 'sistema-de-freio',
    description: 'Pastilhas, discos, fluidos e componentes de freio',
    image: null,
    icon: 'circle-slash',
    parent_id: null,
    order: 3,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    children: [
      {
        id: 'cat-2-1',
        name: 'Pastilhas de Freio',
        slug: 'pastilhas-de-freio',
        description: 'Pastilhas de freio dianteiras e traseiras',
        image: null,
        icon: null,
        parent_id: 'cat-2',
        order: 1,
        is_active: true,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
      },
      {
        id: 'cat-2-2',
        name: 'Discos de Freio',
        slug: 'discos-de-freio',
        description: 'Discos de freio para motos',
        image: null,
        icon: null,
        parent_id: 'cat-2',
        order: 2,
        is_active: true,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
      },
    ],
  },
  {
    id: 'cat-3',
    name: 'Transmissão e Relação',
    slug: 'transmissao-e-relacao',
    description: 'Correntes, pinhões, coroas e relação completa',
    image: null,
    icon: 'git-compare',
    parent_id: null,
    order: 4,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-4',
    name: 'Elétrica e Ignição',
    slug: 'eletrica-e-ignicao',
    description: 'Componentes elétricos e de ignição',
    image: null,
    icon: 'zap',
    parent_id: null,
    order: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-5',
    name: 'Pneus e Câmaras',
    slug: 'pneus-e-camaras',
    description: 'Pneus, câmaras de ar e protetores',
    image: null,
    icon: 'circle',
    parent_id: null,
    order: 5,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-6',
    name: 'Filtros',
    slug: 'filtros',
    description: 'Filtros de óleo, ar e combustível',
    image: null,
    icon: 'filter',
    parent_id: null,
    order: 8,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-7',
    name: 'Lubrificantes',
    slug: 'lubrificantes',
    description: 'Óleos e lubrificantes para motos',
    image: null,
    icon: 'droplet',
    parent_id: null,
    order: 9,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-8',
    name: 'Baterias',
    slug: 'baterias',
    description: 'Baterias para motocicletas',
    image: null,
    icon: 'battery-charging',
    parent_id: null,
    order: 13,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-9',
    name: 'Acessórios',
    slug: 'acessorios',
    description: 'Acessórios para motos e motociclistas',
    image: null,
    icon: 'backpack',
    parent_id: null,
    order: 16,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-10',
    name: 'Capacetes',
    slug: 'capacetes',
    description: 'Capacetes e equipamentos de segurança',
    image: null,
    icon: 'helmet',
    parent_id: null,
    order: 17,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-11',
    name: 'Suspensão',
    slug: 'suspensao',
    description: 'Amortecedores, bengalas e componentes de suspensão',
    image: null,
    icon: 'chevrons-up-down',
    parent_id: null,
    order: 7,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 'cat-12',
    name: 'Escapamentos',
    slug: 'escapamentos',
    description: 'Escapamentos e componentes do sistema de exaustão',
    image: null,
    icon: 'radius',
    parent_id: null,
    order: 14,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
]

export const DEMO_BRANDS: Brand[] = [
  { id: 'brand-1', name: 'Honda', slug: 'honda', logo: null, description: 'Peças originais Honda', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'brand-2', name: 'Yamaha', slug: 'yamaha', logo: null, description: 'Peças originais Yamaha', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'brand-3', name: 'Suzuki', slug: 'suzuki', logo: null, description: 'Peças originais Suzuki', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'brand-4', name: 'Kawasaki', slug: 'kawasaki', logo: null, description: 'Peças originais Kawasaki', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'brand-5', name: 'NGK', slug: 'ngk', logo: null, description: 'Velas e ignição', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'brand-6', name: 'Michellin', slug: 'michelin', logo: null, description: 'Pneus de alta qualidade', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'brand-7', name: 'Pirelli', slug: 'pirelli', logo: null, description: 'Pneus esportivos', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'brand-8', name: 'Pro Tork', slug: 'pro-tork', logo: null, description: 'Peças e acessórios', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'brand-9', name: 'Magnetron', slug: 'magnetron', logo: null, description: 'Componentes elétricos', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'brand-10', name: 'Cobreq', slug: 'cobreq', logo: null, description: 'Pastilhas e lonas de freio', is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
]

const DEMO_COMPATIBILITIES: ProductCompatibility[] = [
  { id: 'comp-1', product_id: 'prod-1', motorcycle_brand: 'Honda', motorcycle_model: 'CG 160 Titan', motorcycle_version: 'KS', year_start: 2016, year_end: 2024, displacement: '160cc', notes: 'Dianteira' },
  { id: 'comp-2', product_id: 'prod-1', motorcycle_brand: 'Honda', motorcycle_model: 'CG 160 Fan', motorcycle_version: null, year_start: 2016, year_end: 2024, displacement: '160cc', notes: 'Dianteira' },
  { id: 'comp-3', product_id: 'prod-2', motorcycle_brand: 'Honda', motorcycle_model: 'CG 150', motorcycle_version: 'Titan', year_start: 2008, year_end: 2015, displacement: '150cc', notes: null },
  { id: 'comp-4', product_id: 'prod-4', motorcycle_brand: 'Honda', motorcycle_model: 'CG 160 Titan', motorcycle_version: null, year_start: 2016, year_end: 2024, displacement: '160cc', notes: 'Óleo semissintético 10W30' },
  { id: 'comp-5', product_id: 'prod-5', motorcycle_brand: 'Honda', motorcycle_model: 'CG 160 Titan', motorcycle_version: null, year_start: 2016, year_end: 2024, displacement: '160cc', notes: 'Original' },
  { id: 'comp-6', product_id: 'prod-6', motorcycle_brand: 'Yamaha', motorcycle_model: 'Fazer 250', motorcycle_version: null, year_start: 2015, year_end: 2024, displacement: '250cc', notes: 'Dianteira' },
]

const createDemoImage = (index: number, alt: string): ProductImage => ({
  id: `img-${index}`,
  product_id: `prod-${index}`,
  url: `/images/placeholder-product.svg`,
  alt,
  order: 0,
  is_primary: true,
})

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Pastilha de Freio Dianteira Cobreq',
    slug: 'pastilha-de-freio-dianteira-cobreq',
    sku: 'MC-0001',
    barcode: null,
    brand_id: 'brand-10',
    brand_name: 'Cobreq',
    category_id: 'cat-2-1',
    category_name: 'Pastilhas de Freio',
    description: 'Pastilha de freio dianteira Cobreq de alta qualidade para Honda CG 160. Fabricada com material sinterizado que oferece excelente poder de frenagem e durabilidade. Ideal para uso urbano e rodoviário.',
    short_description: 'Pastilha de freio dianteira para Honda CG 160 2016 a 2024',
    specifications: { 'Material': 'Sinterizado', 'Posição': 'Dianteira', 'Comprimento': '65mm', 'Largura': '35mm' },
    highlights: ['Alta durabilidade', 'Excelente frenagem', 'Fácil instalação', 'Marca Cobreq'],
    price: 79.90,
    promotional_price: 59.90,
    promotional_ends_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    cost_price: 35.00,
    stock: 15,
    stock_unlimited: false,
    is_active: true,
    is_featured: true,
    is_new: false,
    weight: 0.2,
    length: 10,
    width: 5,
    height: 3,
    warranty: '3 meses',
    installation_info: 'Instalação simples. Recomenda-se verificar o desgaste do disco de freio.',
    meta_title: 'Pastilha de Freio Dianteira Cobreq para Honda CG 160 | Motocar',
    meta_description: 'Pastilha de freio dianteira Cobreq para Honda CG 160 Titan/Fan 2016 a 2024. Qualidade e segurança em Presidente Epitácio.',
    views: 230,
    created_at: '2024-01-15',
    updated_at: '2024-06-01',
    images: [createDemoImage(1, 'Pastilha de Freio Dianteira Cobreq')],
    compatibilities: DEMO_COMPATIBILITIES.filter(c => c.product_id === 'prod-1'),
    variants: [],
  },
  {
    id: 'prod-2',
    name: 'Relação Completa Pro Tork CG 150',
    slug: 'relacao-completa-pro-tork-cg-150',
    sku: 'MC-0002',
    barcode: null,
    brand_id: 'brand-8',
    brand_name: 'Pro Tork',
    category_id: 'cat-3',
    category_name: 'Transmissão e Relação',
    description: 'Kit de relação completa Pro Tork composto por coroa, pinhão e corrente. Fabricado em aço de alta resistência, garantindo durabilidade e desempenho para sua Honda CG 150.',
    short_description: 'Kit relação completa para Honda CG 150 2008 a 2015',
    specifications: { 'Material': 'Aço', 'Dentes Coroa': '43', 'Dentes Pinhão': '15', 'Elos': '120' },
    highlights: ['Kit completo', 'Alta resistência', 'Marca Pro Tork', 'Relação original'],
    price: 189.90,
    promotional_price: 159.90,
    promotional_ends_at: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    cost_price: 90.00,
    stock: 8,
    stock_unlimited: false,
    is_active: true,
    is_featured: true,
    is_new: false,
    weight: 1.5,
    length: 30,
    width: 20,
    height: 10,
    warranty: '6 meses',
    installation_info: 'Recomenda-se substituição completa do kit. Necessário ajuste de tensão após primeiros km.',
    meta_title: 'Relação Completa Pro Tork Honda CG 150 | Motocar',
    meta_description: 'Kit de relação completa Pro Tork para Honda CG 150. Coroa, pinhão e corrente. Frete grátis para Presidente Epitácio.',
    views: 180,
    created_at: '2024-02-01',
    updated_at: '2024-06-01',
    images: [createDemoImage(2, 'Relação Completa Pro Tork')],
    compatibilities: DEMO_COMPATIBILITIES.filter(c => c.product_id === 'prod-2'),
    variants: [
      { id: 'var-1', product_id: 'prod-2', name: 'Relação 43/15', sku: 'MC-0002-A', price: null, stock: 5, is_active: true },
      { id: 'var-2', product_id: 'prod-2', name: 'Relação 42/14', sku: 'MC-0002-B', price: 179.90, stock: 3, is_active: true },
    ],
  },
  {
    id: 'prod-3',
    name: 'Óleo Semissintético 10W30 1 Litro',
    slug: 'oleo-semissintetico-10w30-1l',
    sku: 'MC-0003',
    barcode: null,
    brand_id: null,
    brand_name: 'Mobil',
    category_id: 'cat-7',
    category_name: 'Lubrificantes',
    description: 'Óleo semissintético 10W30 para motos 4 tempos. Proporciona proteção superior ao motor, reduz o atrito e prolonga a vida útil do motor. Ideal para uso urbano.',
    short_description: 'Óleo semissintético 10W30 para motos 4 tempos',
    specifications: { 'Viscosidade': '10W30', 'Capacidade': '1 Litro', 'Tipo': 'Semissintético', 'Aplicação': 'Motos 4 tempos' },
    highlights: ['Proteção superior', 'Reduz atrito', 'Motor mais limpo', 'Alta durabilidade'],
    price: 45.90,
    promotional_price: null,
    promotional_ends_at: null,
    cost_price: 25.00,
    stock: 50,
    stock_unlimited: false,
    is_active: true,
    is_featured: true,
    is_new: false,
    weight: 1.0,
    length: 15,
    width: 10,
    height: 25,
    warranty: null,
    installation_info: null,
    meta_title: 'Óleo Semissintético 10W30 para Motos | Motocar',
    meta_description: 'Óleo semissintético 10W30 1 litro para motos 4 tempos. Proteção e desempenho para seu motor. Entrega em Presidente Epitácio.',
    views: 320,
    created_at: '2024-01-10',
    updated_at: '2024-06-01',
    images: [createDemoImage(3, 'Óleo Semissintético 10W30')],
    compatibilities: [],
    variants: [
      { id: 'var-3', product_id: 'prod-3', name: 'Unidade 1L', sku: 'MC-0003-1', price: null, stock: 50, is_active: true },
      { id: 'var-4', product_id: 'prod-3', name: 'Kit 3 Unidades', sku: 'MC-0003-3', price: 129.90, stock: 20, is_active: true },
    ],
  },
  {
    id: 'prod-4',
    name: 'Filtro de Óleo Original Honda CG 160',
    slug: 'filtro-de-oleo-original-honda-cg-160',
    sku: 'MC-0004',
    barcode: null,
    brand_id: 'brand-1',
    brand_name: 'Honda',
    category_id: 'cat-6',
    category_name: 'Filtros',
    description: 'Filtro de óleo original Honda para CG 160. Garante a filtragem adequada do óleo do motor, removendo impurezas e prolongando a vida útil do motor.',
    short_description: 'Filtro de óleo original Honda CG 160 2016-2024',
    specifications: { 'Marca': 'Honda', 'Tipo': 'Original', 'Aplicação': 'CG 160 Titan/Fan', 'Ano': '2016-2024' },
    highlights: ['Peça original', 'Garantia de qualidade', 'Filtragem eficiente', 'Fácil troca'],
    price: 32.90,
    promotional_price: null,
    promotional_ends_at: null,
    cost_price: 18.00,
    stock: 30,
    stock_unlimited: false,
    is_active: true,
    is_featured: true,
    is_new: false,
    weight: 0.1,
    length: 8,
    width: 8,
    height: 6,
    warranty: null,
    installation_info: 'Substituir a cada troca de óleo. Aplicar uma fina camada de óleo na vedação antes de instalar.',
    meta_title: 'Filtro de Óleo Original Honda CG 160 | Motocar',
    meta_description: 'Filtro de óleo original Honda para CG 160 Titan/Fan 2016-2024. Qualidade original em Presidente Epitácio.',
    views: 200,
    created_at: '2024-03-01',
    updated_at: '2024-06-01',
    images: [createDemoImage(4, 'Filtro de Óleo Original Honda')],
    compatibilities: DEMO_COMPATIBILITIES.filter(c => c.product_id === 'prod-4'),
    variants: [],
  },
  {
    id: 'prod-5',
    name: 'Vela de Ignição NGK CR7HSA',
    slug: 'vela-de-ignicao-ngk-cr7hsa',
    sku: 'MC-0005',
    barcode: null,
    brand_id: 'brand-5',
    brand_name: 'NGK',
    category_id: 'cat-4',
    category_name: 'Elétrica e Ignição',
    description: 'Vela de ignição NGK CR7HSA de alta performance. Proporciona partida rápida, melhor combustão e economia de combustível. Compatível com diversos modelos Honda e Yamaha.',
    short_description: 'Vela de ignição NGK CR7HSA padrão',
    specifications: { 'Marca': 'NGK', 'Modelo': 'CR7HSA', 'Tipo': 'Padrão', 'Rosca': '10mm' },
    highlights: ['Marca NGK', 'Partida rápida', 'Economia de combustível', 'Alta durabilidade'],
    price: 18.90,
    promotional_price: 14.90,
    promotional_ends_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    cost_price: 8.00,
    stock: 100,
    stock_unlimited: false,
    is_active: true,
    is_featured: true,
    is_new: false,
    weight: 0.05,
    length: 6,
    width: 2,
    height: 2,
    warranty: null,
    installation_info: 'Utilizar chave de vela. Não apertar em excesso. Torque recomendado: 15-20 Nm.',
    meta_title: 'Vela de Ignição NGK CR7HSA | Motocar',
    meta_description: 'Vela NGK CR7HSA para Honda CG, Titan e Bros. Partida rápida e economia. Compre na Motocar em Presidente Epitácio.',
    views: 450,
    created_at: '2024-01-05',
    updated_at: '2024-06-01',
    images: [createDemoImage(5, 'Vela de Ignição NGK CR7HSA')],
    compatibilities: DEMO_COMPATIBILITIES.filter(c => c.product_id === 'prod-5'),
    variants: [],
  },
  {
    id: 'prod-6',
    name: 'Pastilha de Freio Dianteira Yamaha Fazer 250',
    slug: 'pastilha-de-freio-dianteira-yamaha-fazer-250',
    sku: 'MC-0006',
    barcode: null,
    brand_id: 'brand-10',
    brand_name: 'Cobreq',
    category_id: 'cat-2-1',
    category_name: 'Pastilhas de Freio',
    description: 'Pastilha de freio dianteira para Yamaha Fazer 250. Material de alta qualidade que garante frenagem segura em qualquer condição. Produto original Cobreq.',
    short_description: 'Pastilha de freio dianteira para Yamaha Fazer 250',
    specifications: { 'Material': 'Semimetálico', 'Posição': 'Dianteira', 'Marca': 'Cobreq' },
    highlights: ['Frenagem segura', 'Material de qualidade', 'Marca Cobreq', 'Fácil instalação'],
    price: 89.90,
    promotional_price: null,
    promotional_ends_at: null,
    cost_price: 42.00,
    stock: 10,
    stock_unlimited: false,
    is_active: true,
    is_featured: true,
    is_new: true,
    weight: 0.25,
    length: 10,
    width: 5,
    height: 3,
    warranty: '3 meses',
    installation_info: 'Verificar nível de fluido de freio após instalação. Amaciar pastilhas nos primeiros 200km.',
    meta_title: 'Pastilha de Freio Dianteira Yamaha Fazer 250 | Motocar',
    meta_description: 'Pastilha de freio dianteira Cobreq para Yamaha Fazer 250. Segurança e qualidade em Presidente Epitácio.',
    views: 120,
    created_at: '2024-05-01',
    updated_at: '2024-06-01',
    images: [createDemoImage(6, 'Pastilha de Freio Yamaha Fazer 250')],
    compatibilities: DEMO_COMPATIBILITIES.filter(c => c.product_id === 'prod-6'),
    variants: [],
  },
  {
    id: 'prod-7',
    name: 'Bateria Moura M30BX para Motos',
    slug: 'bateria-moura-m30bx',
    sku: 'MC-0007',
    barcode: null,
    brand_id: null,
    brand_name: 'Moura',
    category_id: 'cat-8',
    category_name: 'Baterias',
    description: 'Bateria Moura M30BX de 12V para motocicletas. Alta potência de partida e longa vida útil. Ideal para motos de média e alta cilindrada.',
    short_description: 'Bateria Moura 12V para motocicletas',
    specifications: { 'Marca': 'Moura', 'Modelo': 'M30BX', 'Voltagem': '12V', 'Capacidade': '30Ah' },
    highlights: ['Marca Moura', 'Alta potência', 'Longa vida útil', 'Livre de manutenção'],
    price: 249.90,
    promotional_price: 219.90,
    promotional_ends_at: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    cost_price: 130.00,
    stock: 6,
    stock_unlimited: false,
    is_active: true,
    is_featured: true,
    is_new: false,
    weight: 4.5,
    length: 20,
    width: 12,
    height: 18,
    warranty: '12 meses',
    installation_info: 'Verificar polaridade antes de instalar. Descartar bateria usada em local apropriado.',
    meta_title: 'Bateria Moura M30BX para Motos | Motocar',
    meta_description: 'Bateria Moura M30BX 12V 30Ah para motocicletas. Potência e durabilidade. Compre na Motocar em Presidente Epitácio.',
    views: 150,
    created_at: '2024-04-01',
    updated_at: '2024-06-01',
    images: [createDemoImage(7, 'Bateria Moura M30BX')],
    compatibilities: [],
    variants: [],
  },
  {
    id: 'prod-8',
    name: 'Corrente de Transmissão Pro Tork 428',
    slug: 'corrente-de-transmissao-pro-tork-428',
    sku: 'MC-0008',
    barcode: null,
    brand_id: 'brand-8',
    brand_name: 'Pro Tork',
    category_id: 'cat-3',
    category_name: 'Transmissão e Relação',
    description: 'Corrente de transmissão Pro Tork 428 de alta resistência. Fabricada em aço liga tratado termicamente, oferecendo excelente resistência ao desgaste.',
    short_description: 'Corrente de transmissão 428 Pro Tork',
    specifications: { 'Marca': 'Pro Tork', 'Medida': '428', 'Material': 'Aço liga', 'Elos': '120' },
    highlights: ['Alta resistência', 'Aço tratado', 'Durabilidade', 'Marca Pro Tork'],
    price: 89.90,
    promotional_price: null,
    promotional_ends_at: null,
    cost_price: 45.00,
    stock: 20,
    stock_unlimited: false,
    is_active: true,
    is_featured: false,
    is_new: false,
    weight: 1.2,
    length: 60,
    width: 10,
    height: 5,
    warranty: '3 meses',
    installation_info: null,
    meta_title: 'Corrente de Transmissão 428 Pro Tork | Motocar',
    meta_description: 'Corrente de transmissão Pro Tork 428. Resistência e durabilidade para sua moto na Motocar.',
    views: 90,
    created_at: '2024-02-15',
    updated_at: '2024-06-01',
    images: [createDemoImage(8, 'Corrente de Transmissão Pro Tork')],
    compatibilities: [],
    variants: [],
  },
  {
    id: 'prod-9',
    name: 'Filtro de Ar K&N Esportivo',
    slug: 'filtro-de-ar-k-n-esportivo',
    sku: 'MC-0009',
    barcode: null,
    brand_id: null,
    brand_name: 'K&N',
    category_id: 'cat-6',
    category_name: 'Filtros',
    description: 'Filtro de ar esportivo K&N de alto fluxo. Lavável e reutilizável. Aumenta a potência do motor e melhora a aceleração. Durável e econômico.',
    short_description: 'Filtro de ar esportivo K&N lavável e reutilizável',
    specifications: { 'Marca': 'K&N', 'Tipo': 'Esportivo', 'Aplicação': 'Universal', 'Material': 'Algodão' },
    highlights: ['Lavável e reutilizável', 'Aumenta potência', 'Melhor aceleração', 'Econômico'],
    price: 129.90,
    promotional_price: null,
    promotional_ends_at: null,
    cost_price: 65.00,
    stock: 12,
    stock_unlimited: false,
    is_active: true,
    is_featured: false,
    is_new: true,
    weight: 0.3,
    length: 15,
    width: 10,
    height: 10,
    warranty: null,
    installation_info: null,
    meta_title: 'Filtro de Ar Esportivo K&N | Motocar',
    meta_description: 'Filtro de ar K&N esportivo lavável. Mais potência e economia. Na Motocar em Presidente Epitácio.',
    views: 75,
    created_at: '2024-05-15',
    updated_at: '2024-06-01',
    images: [createDemoImage(9, 'Filtro de Ar K&N')],
    compatibilities: [],
    variants: [],
  },
  {
    id: 'prod-10',
    name: 'Capacete Pro Tork Evolution Fechado',
    slug: 'capacete-pro-tork-evolution-fechado',
    sku: 'MC-0010',
    barcode: null,
    brand_id: 'brand-8',
    brand_name: 'Pro Tork',
    category_id: 'cat-10',
    category_name: 'Capacetes',
    description: 'Capacete fechado Pro Tork Evolution com viseira clara. Confortável e seguro, atende às normas do INMETRO. Ideal para uso urbano e viagens.',
    short_description: 'Capacete fechado Pro Tork Evolution com viseira',
    specifications: { 'Marca': 'Pro Tork', 'Modelo': 'Evolution', 'Tipo': 'Fechado', 'Norma': 'INMETRO' },
    highlights: ['Aprovado INMETRO', 'Confortável', 'Viseira inclusa', 'Bom custo-benefício'],
    price: 199.90,
    promotional_price: 169.90,
    promotional_ends_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    cost_price: 100.00,
    stock: 5,
    stock_unlimited: false,
    is_active: true,
    is_featured: false,
    is_new: false,
    weight: 1.5,
    length: 35,
    width: 25,
    height: 25,
    warranty: null,
    installation_info: null,
    meta_title: 'Capacete Pro Tork Evolution Fechado | Motocar',
    meta_description: 'Capacete fechado Pro Tork Evolution aprovado INMETRO. Conforto e segurança em Presidente Epitácio.',
    views: 200,
    created_at: '2024-03-10',
    updated_at: '2024-06-01',
    images: [createDemoImage(10, 'Capacete Pro Tork Evolution')],
    compatibilities: [],
    variants: [],
  },
]

export const DEMO_SERVICES: Service[] = [
  {
    id: 'srv-1',
    name: 'Revisão de Motos',
    slug: 'revisao-de-motos',
    summary: 'Revisão completa para sua moto',
    description: 'Revisão geral incluindo verificação de motor, freios, suspensão, transmissão, elétrica e fluidos. Garantimos que sua moto saia da oficina em perfeitas condições.',
    image: null,
    benefits: ['Diagnóstico completo', 'Verificação de todos os sistemas', 'Relatório detalhado', 'Garantia dos serviços'],
    duration: '2 a 4 horas',
    price_min: 120.00,
    price_max: 350.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'srv-2',
    name: 'Troca de Óleo',
    slug: 'troca-de-oleo',
    summary: 'Troca de óleo com filtro',
    description: 'Troca de óleo do motor com substituição do filtro de óleo. Utilizamos óleos de alta qualidade das melhores marcas.',
    image: null,
    benefits: ['Óleo de qualidade', 'Filtro novo incluso', 'Motor protegido', 'Maior durabilidade'],
    duration: '30 minutos',
    price_min: 60.00,
    price_max: 120.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'srv-3',
    name: 'Troca de Relação',
    slug: 'troca-de-relacao',
    summary: 'Substituição de coroa, pinhão e corrente',
    description: 'Substituição completa do kit de relação. Utilizamos peças de qualidade para garantir segurança e desempenho.',
    image: null,
    benefits: ['Kit completo', 'Ajuste profissional', 'Maior segurança', 'Durabilidade'],
    duration: '1 a 2 horas',
    price_min: 80.00,
    price_max: 150.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'srv-4',
    name: 'Manutenção de Freios',
    slug: 'manutencao-de-freios',
    summary: 'Substituição de pastilhas e verificação do sistema',
    description: 'Verificação completa do sistema de freios, substituição de pastilhas, verificação de discos e fluido de freio.',
    image: null,
    benefits: ['Segurança garantida', 'Pastilhas novas', 'Fluido verificado', 'Freios eficientes'],
    duration: '1 a 2 horas',
    price_min: 70.00,
    price_max: 200.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'srv-5',
    name: 'Troca de Pneus',
    slug: 'troca-de-pneus',
    summary: 'Substituição e balanceamento de pneus',
    description: 'Troca de pneus dianteiros e traseiros com balanceamento. Trabalhamos com as principais marcas do mercado.',
    image: null,
    benefits: ['Pneus de qualidade', 'Balanceamento incluso', 'Segurança', 'Melhor aderência'],
    duration: '1 hora',
    price_min: 50.00,
    price_max: 100.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'srv-6',
    name: 'Manutenção Elétrica',
    slug: 'manutencao-eletrica',
    summary: 'Diagnóstico e reparo elétrico',
    description: 'Diagnóstico completo do sistema elétrico, reparo de falhas, substituição de componentes e verificacão de carga da bateria.',
    image: null,
    benefits: ['Diagnóstico preciso', 'Reparo especializado', 'Sistema confiável', 'Partida garantida'],
    duration: '1 a 3 horas',
    price_min: 80.00,
    price_max: 250.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'srv-7',
    name: 'Limpeza e Revisão de Injeção',
    slug: 'limpeza-revisao-injecao',
    summary: 'Limpeza e manutenção do sistema de injeção',
    description: 'Limpeza dos bicos injetores, verificação da bomba de combustível e sensores. Essencial para o bom funcionamento do motor.',
    image: null,
    benefits: ['Motor mais económico', 'Melhor desempenho', 'Redução de emissões', 'Partida facilitada'],
    duration: '2 a 3 horas',
    price_min: 150.00,
    price_max: 300.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'srv-8',
    name: 'Substituição de Filtros',
    slug: 'substituicao-de-filtros',
    summary: 'Troca de filtros de ar, óleo e combustível',
    description: 'Substituição de todos os filtros da sua moto. Filtros limpos garantem melhor performance e maior vida útil do motor.',
    image: null,
    benefits: ['Motor protegido', 'Melhor performance', 'Economia', 'Filtros originais'],
    duration: '30 minutos',
    price_min: 40.00,
    price_max: 90.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'srv-9',
    name: 'Diagnóstico de Falhas',
    slug: 'diagnostico-de-falhas',
    summary: 'Diagnóstico eletrônico de falhas',
    description: 'Utilizamos equipamentos modernos para diagnóstico preciso de falhas mecânicas e elétricas. Identificamos problemas rapidamente.',
    image: null,
    benefits: ['Diagnóstico rápido', 'Equipamento moderno', 'Precisão', 'Orçamento sem surpresas'],
    duration: '30 a 60 minutos',
    price_min: 50.00,
    price_max: 150.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'srv-10',
    name: 'Manutenção Preventiva',
    slug: 'manutencao-preventiva',
    summary: 'Programa de manutenção preventiva completa',
    description: 'Programa completo de manutenção preventiva para sua moto. Inclui verificação de todos os sistemas e substituição de itens conforme o manual do fabricante.',
    image: null,
    benefits: ['Moto sempre pronta', 'Evita quebras', 'Maior durabilidade', 'Economia a longo prazo'],
    duration: '2 a 4 horas',
    price_min: 150.00,
    price_max: 400.00,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
]

export const DEMO_BANNERS: Banner[] = [
  {
    id: 'banner-1',
    title: 'Peças para sua moto com atendimento de quem entende',
    subtitle: 'Encontre peças, acessórios e serviços para manter sua moto segura e pronta para rodar.',
    image: '/images/placeholder-banner.svg',
    link: '/produtos',
    button_text: 'Ver produtos',
    button_text_secondary: 'Falar com a Motocar',
    link_secondary: '#contato',
    order: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'banner-2',
    title: 'Revisão e manutenção de motos em Presidente Epitácio',
    subtitle: 'Agende uma revisão completa para sua moto com nossa equipe especializada.',
    image: '/images/placeholder-banner.svg',
    link: '/agendamento',
    button_text: 'Agendar serviço',
    button_text_secondary: 'Conhecer a oficina',
    link_secondary: '/servicos',
    order: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'banner-3',
    title: 'Não sabe qual peça serve na sua moto?',
    subtitle: 'Consulte nossa equipe pelo WhatsApp e descubra a peça certa para sua motocicleta.',
    image: '/images/placeholder-banner.svg',
    link: '#',
    button_text: 'Consultar pelo WhatsApp',
    button_text_secondary: null,
    link_secondary: null,
    order: 3,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
]

export const DEMO_POSTS: BlogPost[] = [
  {
    id: 'post-1',
    title: 'Quando trocar o óleo da moto? Guia completo',
    slug: 'quando-trocar-o-oleo-da-moto',
    excerpt: 'Saber o momento certo de trocar o óleo do motor é essencial para a durabilidade da sua motocicleta. Confira nosso guia completo.',
    content: `<h2>Por que a troca de óleo é importante?</h2>
<p>O óleo do motor é responsável por lubrificar, limpar e refrigerar as partes internas do motor. Com o tempo, ele perde suas propriedades e precisa ser substituído.</p>
<h2>Qual a frequência ideal?</h2>
<p>Para a maioria das motos, a troca de óleo deve ser feita a cada 3.000 km ou 6 meses, o que ocorrer primeiro. Motos com óleo sintético podem rodar até 5.000 km entre trocas.</p>
<h3>Sinais de que o óleo precisa ser trocado</h3>
<ul>
<li>Nível baixo no visor</li>
<li>Cor escura ou queimada</li>
<li>Consistência muito fina</li>
<li>Barulho incomum do motor</li>
<li>Dificuldade na partida</li>
</ul>
<h2>Tipos de óleo para motos</h2>
<p><strong>Mineral:</strong> Indicado para motos antigas ou com motor desgastado. Troca a cada 2.000 km.</p>
<p><strong>Semissintético:</strong> O mais utilizado. Equilíbrio entre custo e proteção. Troca a cada 3.000 km.</p>
<p><strong>Sintético:</strong> Máxima proteção. Indicado para motos esportivas e de alta cilindrada. Troca a cada 5.000 km.</p>
<h2>O que mais verificar na troca?</h2>
<p>Aproveite a troca de óleo para substituir também o filtro de óleo. Isso garante que o óleo novo não seja contaminado por resíduos retidos no filtro antigo.</p>
<h2>Conte com a Motocar</h2>
<p>Na Motocar, em Presidente Epitácio, realizamos troca de óleo com produtos de qualidade e mão de obra especializada. Agende seu horário!</p>`,
    image: null,
    author: 'Equipe Motocar',
    category_id: 'bc-1',
    category_name: 'Manutenção de Motos',
    reading_time: 5,
    is_published: true,
    published_at: '2024-05-20',
    meta_title: 'Quando trocar o óleo da moto? | Motocar',
    meta_description: 'Guia completo sobre troca de óleo de moto. Frequência, tipos de óleo e dicas para aumentar a vida útil do motor. Motocar em Presidente Epitácio.',
    created_at: '2024-05-20',
    updated_at: '2024-06-01',
  },
  {
    id: 'post-2',
    title: 'Como saber se a relação da moto está desgastada?',
    slug: 'como-saber-se-a-relacao-da-moto-esta-desgastada',
    excerpt: 'A relação é um dos componentes mais importantes da transmissão. Saiba identificar os sinais de desgaste e quando substituir.',
    content: `<h2>O que é a relação da moto?</h2>
<p>A relação é o conjunto formado por coroa, pinhão e corrente, responsável por transmitir a força do motor para a roda traseira.</p>
<h2>Sinais de desgaste</h2>
<h3>Na corrente</h3>
<ul>
<li>Folga excessiva mesmo após ajuste</li>
<li>Elos duros ou travados</li>
<li>Ferrugem visível</li>
<li>Estalos ao andar</li>
</ul>
<h3>Na coroa e pinhão</h3>
<ul>
<li>Dentes com pontas afiadas</li>
<li>Dentes quebrados ou tortos</li>
<li>Desgaste em formato de gancho</li>
</ul>
<h2>Quando substituir?</h2>
<p>Recomenda-se substituir o kit completo quando a corrente apresenta mais de 1% de alongamento em relação ao tamanho original, ou quando há danos visíveis em qualquer componente.</p>
<h2>Duração média</h2>
<p>Com manutenção adequada, um kit de relação pode durar entre 15.000 e 25.000 km, dependendo do modelo da moto e das condições de uso.</p>
<h2>Na Motocar você encontra</h2>
<p>Temos kits de relação para diversos modelos de motos. Consulte nossa equipe em Presidente Epitácio para escolher o kit ideal para sua moto.</p>`,
    image: null,
    author: 'Equipe Motocar',
    category_id: 'bc-1',
    category_name: 'Manutenção de Motos',
    reading_time: 4,
    is_published: true,
    published_at: '2024-06-01',
    meta_title: 'Como saber se a relação da moto está desgastada? | Motocar',
    meta_description: 'Aprenda a identificar os sinais de desgaste da relação da sua moto e saiba quando substituir coroa, pinhão e corrente.',
    created_at: '2024-06-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'post-3',
    title: 'Filtro de ar sujo pode fazer a moto perder força?',
    slug: 'filtro-de-ar-sujo-pode-fazer-moto-perder-forca',
    excerpt: 'O filtro de ar é essencial para o funcionamento do motor. Descubra como um filtro sujo afeta o desempenho da sua motocicleta.',
    content: `<h2>Qual a função do filtro de ar?</h2>
<p>O filtro de ar impede que impurezas, poeira e partículas entrem no motor, garantindo que apenas ar limpo participe da combustão.</p>
<h2>Sinais de filtro sujo</h2>
<ul>
<li>Perda de potência</li>
<li>Aumento no consumo de combustível</li>
<li>Dificuldade na partida</li>
<li>Marcha lenta irregular</li>
<li>Fumaça escura no escapamento</li>
</ul>
<h2>Quando trocar?</h2>
<p>O filtro de ar deve ser verificado a cada 3.000 km e substituído a cada 6.000 km ou conforme recomendação do fabricante. Em regiões com muita poeira, a frequência deve ser maior.</p>
<h2>Filtro lavável vs. descartável</h2>
<p>Filtros descartáveis são substituídos por novos. Já os filtros laváveis (como K&N) podem ser limpos e reutilizados, sendo mais econômicos a longo prazo.</p>
<h2>Troque seu filtro na Motocar</h2>
<p>Na Motocar, em Presidente Epitácio, realizamos a substituição de filtros de ar, óleo e combustível. Agende seu horário e mantenha sua moto em dia.</p>`,
    image: null,
    author: 'Equipe Motocar',
    category_id: 'bc-3',
    category_name: 'Peças e Acessórios',
    reading_time: 4,
    is_published: true,
    published_at: '2024-06-10',
    meta_title: 'Filtro de ar sujo pode fazer a moto perder força? | Motocar',
    meta_description: 'Entenda como o filtro de ar sujo afeta o desempenho da sua moto. Saiba os sinais e quando trocar o filtro. Motocar em Presidente Epitácio.',
    created_at: '2024-06-10',
    updated_at: '2024-06-10',
  },
  {
    id: 'post-4',
    title: 'Quais sinais indicam problemas no freio da moto?',
    slug: 'sinais-problemas-freio-moto',
    excerpt: 'Os freios são o item de segurança mais importante da sua moto. Fique atento a estes sinais de desgaste.',
    content: `<h2>Importância dos freios</h2>
<p>Manter o sistema de freios em perfeito estado é fundamental para sua segurança. Qualquer alteração no funcionamento deve ser investigada imediatamente.</p>
<h2>Principais sinais de problema</h2>
<ul>
<li>Barulho ao frear (chiado ou rangido)</li>
<li>Vibração no guidão ao frear</li>
<li>Curso longo da manete</li>
<li>Freio "borrachudo" ou muito duro</li>
<li>Vazamento de fluido</li>
<li>Luz de freio acesa no painel</li>
</ul>
<h2>Verificação periódica</h2>
<p>Verifique o nível do fluido de freio mensalmente. As pastilhas devem ser inspecionadas a cada 5.000 km e substituídas quando atingirem 2mm de espessura.</p>
<h2>Na Motocar</h2>
<p>Oferecemos manutenção completa de freios em Presidente Epitácio. Traga sua moto para uma verificação gratuita.</p>`,
    image: null,
    author: 'Equipe Motocar',
    category_id: 'bc-5',
    category_name: 'Oficina',
    reading_time: 3,
    is_published: true,
    published_at: '2024-06-15',
    meta_title: 'Sinais de problemas no freio da moto | Motocar',
    meta_description: 'Saiba identificar problemas nos freios da sua moto. Sinais de desgaste, verificação e manutenção em Presidente Epitácio.',
    created_at: '2024-06-15',
    updated_at: '2024-06-15',
  },
  {
    id: 'post-5',
    title: 'Como aumentar a vida útil da sua motocicleta',
    slug: 'como-aumentar-vida-util-da-sua-motocicleta',
    excerpt: 'Com cuidados simples e manutenção regular, sua moto pode durar muitos anos. Confira nossas dicas.',
    content: `<h2>Cuidados que fazem diferença</h2>
<p>Uma moto bem cuidada não apenas dura mais, como também oferece mais segurança e melhor desempenho.</p>
<h2>Dicas essenciais</h2>
<h3>1. Respeite as revisões</h3>
<p>Siga o plano de manutenção do fabricante. As revisões periódicas são essenciais para identificar problemas antes que se tornem graves.</p>
<h3>2. Use peças de qualidade</h3>
<p>Peças originais ou de marcas reconhecidas garantem o funcionamento adequado e maior durabilidade.</p>
<h3>3. Lubrificação correta</h3>
<p>Mantenha a corrente lubrificada e o óleo do motor sempre no nível correto.</p>
<h3>4. Evite sobrecarga</h3>
<p>Não exceda a capacidade de carga da moto. O excesso de peso sobrecarrega suspensão, freios e pneus.</p>
<h3>5. Guarde em local coberto</h3>
<p>Proteger a moto do sol e da chuva prolonga a vida útil da pintura, borrachas e componentes elétricos.</p>
<h2>Conte com a Motocar</h2>
<p>Em Presidente Epitácio, a Motocar é sua parceira na manutenção e cuidados com sua motocicleta.</p>`,
    image: null,
    author: 'Equipe Motocar',
    category_id: 'bc-2',
    category_name: 'Dicas para Motociclistas',
    reading_time: 5,
    is_published: true,
    published_at: '2024-06-20',
    meta_title: 'Como aumentar a vida útil da sua motocicleta | Motocar',
    meta_description: 'Dicas práticas para aumentar a vida útil da sua moto. Cuidados, manutenção e peças de qualidade em Presidente Epitácio.',
    created_at: '2024-06-20',
    updated_at: '2024-06-20',
  },
]

export const DEMO_BLOG_CATEGORIES = [
  { id: 'bc-1', name: 'Manutenção de Motos', slug: 'manutencao-de-motos', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'bc-2', name: 'Dicas para Motociclistas', slug: 'dicas-para-motociclistas', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'bc-3', name: 'Peças e Acessórios', slug: 'pecas-e-acessorios', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'bc-4', name: 'Segurança', slug: 'seguranca', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'bc-5', name: 'Oficina', slug: 'oficina', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'bc-6', name: 'Pneus', slug: 'pneus', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'bc-7', name: 'Freios', slug: 'freios', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'bc-8', name: 'Motor', slug: 'motor', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'bc-9', name: 'Elétrica', slug: 'eletrica', created_at: '2024-01-01', updated_at: '2024-01-01' },
]

export const DEMO_SITE_SETTINGS: Record<string, string> = {
  company_name: 'Motocar',
  company_phone: '(18) 3281-7353',
  company_email: 'contato@motocar.com.br',
  company_address: 'Av. Presidente Vargas, 4-03 - Centro, Presidente Epitácio - SP',
  company_cnpj: '59.002.817/0001-41',
  business_hours: 'Seg a Sex: 08h - 18h | Sáb: 08h - 12h',
  whatsapp_number: '551832817353',
  instagram_url: 'https://instagram.com/motocar.epitacio',
  facebook_url: '#',
  youtube_url: '#',
}
